### ISSUE TITLE
Hard time trying to migrate an existing ontology

### ISSUE THREAD

**Issue by luanfg** [INCATools/ontology-development-kit#1041]
We have a suite of ontologies mostly for dealing with the geological domain. I'm trying to make all the ontologies conformant with OBO principles and trying to use the ODK kit for doing that. I get that there is no easy way to do that yet so what I'm trying to do is to create a "new repo" and try to adapt everything to the repos we already have. 

I will try to list my doubts below:

1) Having trouble handling imports. Most of the imports aren't from OBO so it is not as simple as adding the ontology's ID in the products list to import it. I've read different documentations but, as far as I understand, everytime it assumes that you could find the ontology within the OBO. How could I add an "external" import?

2) On top of the question above: it is common practice to release some stable version as a zip of the github repo and point the ontology URI to the main OWL file. However, when newer versions are released the URI points to the newest version and the oldest version ceases to have a valid online URL. I'm not sure how to keep using that older version of the ontology for the import. Should I manually put it into the mirror folder and then on repo updates block the download of the imported ontology?

3) I'm trying to work with BFO 2020 but the only direct import I can manage is BFO 2.0. I guess that could be solved if I solve problem 1 but since it is an OBO ontology I would like to know if is there any other way.

4) Merging vs importing. Sometimes I would like to import a whole ontology into my own ontology. It is not exactly a merge because I still want to have the imported ontology in a distinct owl file. Is that possible or I should merge the file?

Sorry for all the questions but I've been facing these problems for quite sometime and couldn't figure how to do it by myself.

Cheers,
Luan

**Comment by matentzn** [comment]
@luanfg thanks for reaching out.

> Having trouble handling imports. Most of the imports aren't from OBO so it is not as simple as adding the ontology's ID in the products list to import it. I've read different documentations but, as far as I understand, everytime it assumes that you could find the ontology within the OBO. How could I add an "external" import?

Here is an example on how we include a completely custom import (wikidata) in VBO:

1. ODK config: https://github.com/monarch-initiative/vertebrate-breed-ontology/blob/c52df4d514a71964b4c1d8bcf47a022dcf5fb56a/src/ontology/vbo-odk.yaml#L21
2. Custom import: https://github.com/monarch-initiative/vertebrate-breed-ontology/blob/c52df4d514a71964b4c1d8bcf47a022dcf5fb56a/src/ontology/vbo.Makefile#L62

However, you dont even need something totally custom. You can also:

1. set the `mirror_from` property: https://github.com/monarch-initiative/vertebrate-breed-ontology/blob/c52df4d514a71964b4c1d8bcf47a022dcf5fb56a/src/ontology/vbo-odk.yaml#L18

This should work for most cases of external ontologies.

> On top of the question above: it is common practice to release some stable version as a zip of the github repo and point the ontology URI to the main OWL file. However, when newer versions are released the URI points to the newest version and the oldest version ceases to have a valid online URL. I'm not sure how to keep using that older version of the ontology for the import. Should I manually put it into the mirror folder and then on repo updates block the download of the imported ontology?

While this is uncommon, you can set the the `mirror_from` property in the import to using the version IRI. I have not example in RL at hand but this will work:

```
- id: mondo
   mirror_from: http://purl.obolibrary.org/obo/mondo/releases/2022-06-11/mondo.owl
```

> I'm trying to work with BFO 2020 but the only direct import I can manage is BFO 2.0. I guess that could be solved if I solve problem 1 but since it is an OBO ontology I would like to know if is there any other way.

Does the above answer the question? There should be no problem with using BFO 2020.

> Merging vs importing. Sometimes I would like to import a whole ontology into my own ontology. It is not exactly a merge because I still want to have the imported ontology in a distinct owl file. Is that possible or I should merge the file?

ODK, by default follows a set of well defined release products: https://oboacademy.github.io/obook/explanation/owl-format-variants/#overview-of-the-relevant-concepts

None of them preserve owl:imports statements, because unless they correspond to version IRIs, cannot themselves be versioned properly, and a lot of tools have difficulty handling these.

So the easy answer is no. The slighty harder answer:

You can define a `custom` release product ([example](https://github.com/obophenotype/uberon/blob/f33fde102f005c892537e116532ce06d7293a2d7/src/ontology/uberon-odk.yaml#L23)) and do with it as you please. I would not recommend it through to release ontologies with owl:imports statements - its better to merge the content to have a full record of the versioned axioms.

**Comment by luanfg** [comment]
Thank you @matentzn . I will try as you suggest and let you know the result :)

**Comment by matentzn** [comment]
I made my comments directly on https://github.com/BDI-UFRGS/GeoCoreOntology/pull/6

> Another thing that I noticed is that when I run the repo_update script it creates inside src/ontology a target folder with the same structure and with the owl files inside target/src/ontology. Is that expected to happen?

yep this is how the update mechanism work: the ODK template system generate the new files according to the updated config, and then copies the relevant files from this temporary location into the main location.

**Comment by luanfg** [comment]
I really appreciate your help and your time @matentzn !
I've made my comments there as well. Sadly still have some errors...

**Comment by anitacaron** [comment]
It seems that all issues in the PR https://github.com/BDI-UFRGS/GeoCoreOntology/pull/6 were addressed, so I am closing here, too. 😄
