### ISSUE TITLE
Is it possible to suppress the mirror goal when running make?

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#151]
For large ontologies with even larger imports, waiting for the mirrors to be downloaded can be a chore (PR, for example, takes about 30 min to mirror). My feeling is mirrors should only be downloaded if the file is actually newer. What do you think of this:
Instead of using ROBOT to download, we wget the file. Using the -N option, we tell wget to only download if the file has changed, like so

```
wget -N http://www.some-url.com/import.owl
```

@cmungall ?

**Comment by cmungall** [comment]
The -N option doesn't work in a variety of scenarios AFACIR, dependent on
back-end, of which we have many: S3, FTP, GitHub, Apache

But agree with you this is a problem.

Other ideas:

 - Make a robot sniff option to mirror. Proceed only if first N lines do
not contain identical versionIRI to local file
 - Additional OBO-level standards, e.g. include a .md5 with each release,
or have large ontologies distribute bdbags

**Comment by jamesaoverton** [comment]
I tend to stick to a specific version of each upstream ontology, rather than using the latest.

Checking whether an ontology has been updated properly is not very easy. @rctauber and I started working on a tools for caching and syncing ontologies, but haven't used it in production yet: <https://github.com/knocean/ontofetch>. For an OBO PURL you could see whether the version IRI has changed. For HTTP more generally, after following a series of redirects, you can try to compare `ETag` and `Last-Modified` headers. For FTP I think you're stuck.

If we had our own infrastructure for these things we could do more, but that's taking on a lot of responsibility.

**Comment by cmungall** [comment]
I think sticking to a particular version is the long term way to go

Unfortunately at the moment some of the most commonly used larger ontologies like chebi don't yet have resolvable versionIRIs: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/214

**Comment by matentzn** [comment]
In the absence of a generic solution now, is there any way we can somehow configure make to manually suppress certain goals, like mirror/*.owl (short of changing the Makefile)? Something like: if you already mirrored this week, dont mirror again? I feel you should be able to hack it, like with an intermediate goal somehow, it just eludes me right now.

**Comment by cmungall** [comment]
You can simply choose not to trigger a re download in the yaml.  This will
cache forever until mirror file is manually removed

**Comment by matentzn** [comment]
(this is possible using MIR=false as a make parameter)
