### ISSUE TITLE
Fix Docker 123 errors when external.txt contains CRLF line endings

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#271]
Solution:

```
$(PATTERNDIR)/dosdp-patterns: .FORCE
    sed -i 's/\r\n/\n/g' $(PATTERNDIR)/dosdp-patterns/external.txt
    cat $(PATTERNDIR)/dosdp-patterns/external.txt | sed 's!.*/!!' | sed 's! !!g' |  xargs -I{} rm -f $(PATTERNDIR)/dosdp-patterns/{}
    cat $(PATTERNDIR)/dosdp-patterns/external.txt | sed 's! !!g' | xargs -I{} wget -q {} -P $(PATTERNDIR)/dosdp-patterns
```

Probably better to do something along these lines: https://help.github.com/en/articles/configuring-git-to-handle-line-endings#per-repository-settings

But as a quick hack, this will suffice. Thans @jseager7

**Comment by jseager7** [comment]
Just a note, you might want to use this for the `sed` part:

**Comment by matentzn** [comment]
Cheers, will do.

**Comment by jseager7** [comment]
Having done some more testing it looks like `-r` just enables _extended_ regular expressions, and in my environment the `\R` character class still works without the `-r` flag. Apparently using the `-ir` flags together rather than separately, as `-i -r`, can cause issues when replacing, so if you notice any problems you might just want to fall back to `-i` as the only flag.

**Comment by jseager7** [comment]
@matentzn Now that I've actually tested in the ODK environment, it seems my [previous comment](https://github.com/INCATools/ontology-development-kit/issues/271#issuecomment-520410699) was wrong as well. I didn't realise (or forgot) that `sed` operates line by line, meaning it will never match `\r\n` because the `\n` is excluded from the input when the line is read.

It seems what we want is to remove the `\r` before the end of the line, so this is the command that should actually work (and this was tested by patching the Makefile and running it):

```
sed -i 's/\r$$//g' $(PATTERNDIR)/dosdp-patterns/external.txt
```
Note that the double `$$` is needed to escape the Regex meta-character for line-end `$`, to stop it being parsed by the Makefile. If you just want to remove `\r` everywhere and don't care about whether it occurs at a line end or not (which makes sense in this case), then the following command will work too:

 ```
sed -i 's/\r//g' $(PATTERNDIR)/dosdp-patterns/external.txt
```
