### ISSUE TITLE
Please clarify repo structure for import files

### ISSUE THREAD

**Issue by ramonawalls** [INCATools/ontology-development-kit#273]
I have updated the PCO repo to be consistent with the structure created by the ODK, but I don't understand why there are two import directories (one in root and one under src/ontology). I assume that the ones under /imports are the release import files, and the ones under /src/ontology/imports are the files to work with during editing, but for those ontologies that merge imports before release (like PCO), we don't really need to make release versions of the import files. Keeping the ontology IRIs functional during editing requires them to point to /src/ontology/imports, which add another layer of confusion.

I'm wondering what workflow other ontologies use. How do you manage imports in the editor's file? When do you update the files under /imports? Do you create PURLs for your import files with each release (realizing that not everyone merges imports at release, #175)?

**Comment by matentzn** [comment]
Hey @ramonawalls!

All great questions! Here some attempt at answers:

> I don't understand why there are two import directories (...). I assume that the ones under /imports are the release import files, and the ones under /src/ontology/imports are the files to work with during editing, but for those ontologies that merge imports before release (like PCO), we don't really need to make release versions of the import files.

You are absolutely right. src/ontogy/imports are the imports you can see during editing; the ones under the root directory are those that would be resolved, typically, by the OBO purl configuration in case a release file (pco.owl) would point to them. There used to be some good reason for this: recreating imports could cause inconsistent classes, and we wanted to be sure that whatever import files are used by a release, are definitely consistent with the main ontology (hence the separation of edit-imports and release-imports).

> Keeping the ontology IRIs functional during editing requires them to point to /src/ontology/imports, which add another layer of confusion.

This is done only to manage how imports should resolve locally when opening the edit file, and this is all done by default in the catalogue-001.xml file in src/ontology (see below for recommended process).

All this said, this approach (releasing ontologies with import statements) had one massive shortcoming: Since imports are not versioned (they _always_ point to the latest version!), old ontology versions were not, strictly speaking FAIR: Whenever an import changed on the repositories MASTER branch, the old ontology version would look a bit different. Therefore, we recommend now the following process.

1. Imports in the editors file (pco-edit.owl) are done via purls (`Import(<www.obo.org/o/imports/t_import.owl>)`)
2. The catalog-001.xml in `src/ontology` redirects those imports to the local directory when opening the ontology in Protege. For example, the import `Import(<www.obo.org/o/imports/t_import.owl>)` would be redirected to the `src/ontology/imports` directory.
3. When ontologies are released, all imports are **merged in**, i.e. `o.owl` in the top level directory will have no imports statements. This way, the whole ontology is properly versioned, and becomes FAIR.
4. Imports can be refreshed whenever needed easily by running `sh run.sh make all_imports`; this command will mirror the dependencies (like say BFO and PATO), extract a module and place it in `src/ontology/import`. That way, changes to the imports show up immediately in Protege (even before committing and pushing changes!).

Now all this said: you are of course still allowed to construct some kind of release artefact including import statements, if you really want to. But to be FAIR, you would have to make sure that import PURLS are actually version IRIs pointing to the versioned versions of the imports :D . But I have yet to come across an argument for that I find convincing.. @cmungall @dosumis @balhoff may have slightly different views, but the ODK now implements the above workflow.

**Comment by matentzn** [comment]
@ramonawalls The best thing to do is this:

1. Create a config file for PCO like [this](https://github.com/INCATools/ontology-development-kit/blob/master/examples/phenotype-ontologies/wbphenotype-odk.yaml). 
1. Follow the instructions [here](https://github.com/INCATools/ontology-development-kit) to create a new PCO repo with the ODK.
1. Inspect the Makefile (`target/pco/src/ontology/Makefile`). This is where all current ODK goodies can be found, including all_imports

Now the proper migration from an old ODK to the newest version is not trivial; a lot of things happened. But you can use, for now, the Makefile generated above as inspiration to augment your own. Ideally, we would schedule one day a full migration to the latest ODK :)

Re imports; I agree it is not anymore strictly necessary; We just do this at the moment to maintain a tiny bit of backwards compatibility. If it is too annoying, maybe we can vote to remove them in a separate ticket, but currently I feel we are better served with preserving them.

**Comment by cmungall** [comment]
I agree with you all pragmatically

What is unsatisfying is that there is information in the imports graph.
This is useful to retain, e.g. when loading into a triplestore (mapping
owl:Ontology to NG). We lose this when we merge. The need to merge would be
less if we had sensible formats that allowed packaging of multiple
artefacts (ontologies, NGs) into one file (e.g. owlzip, trig).

But we have the specs and the stacks that we do, so if we want to retain
the information in the imports hierarchy we have to ad-hoc it (e.g.
annotate axioms with rdfs:definedBy etc).

Note in obojson there can be multiple ontologies in one file. But to keep
it isomorphic with the owl we must merge.

I would like to step back a bit here and plan things well for the future.
The whole idea of an imports module to be released is problematic (but the
least worst option given various constraints). It would be nice if this all
worked as with software.

**Comment by cmungall** [comment]
Basically we need better ways of working with base files. Ideally loading a
triplestore would just take base files, but previous versions of linked
ontologies would be stored allowing for consistent states. Ideally base
files would look less weird when using owl toolchains (e.g. dynamic
resolution of dangling classes).

**Comment by matentzn** [comment]
So at least implicitly, the existence of the imports directory (in the release dir) including all relevant import modules kind of models the 'depends on' relationship for base files. I understand this is not satisfying, but perhaps an indication that we should, for now, continue to generate release modules, until we find a nice way to connect them. We should one day meet again @cmungall to better understand the ideal 'future' of here, I am happy to support the evolution of the tool-chains to that end.

**Comment by ramonawalls** [comment]
Thanks everyone for more detailed and thoughtful discussion than I expected!

@matentzn Thanks for the instructions for fitting PCO to the latest ODK. Not sure I'll have time for that in the immediate future, but it is good to know how to do it.

**Comment by matentzn** [comment]
I will close this now! @ramonawalls let me know if I can help! I have migrated more than 20 repos, I am happy to support you as well to get OBO spread OBO release guidelines and quality control everywhere :P
