### ISSUE TITLE
What's the easiest way to use this to validate an OBO in TravisCI?

### ISSUE THREAD

**Issue by chambm** [INCATools/ontology-development-kit#349]
I want to add CI validation of our OBO file that runs when PRs are made. Is there an example of someone using ODK like this (or fastobo-validator, which seems included in ODK)? Would probably be a good thing to have in the README if so.

**Comment by matentzn** [comment]
We have no example using fastobo, but since that is in the ODK it should be easy. The most complex job I can think off as an example is this one: 

https://github.com/obophenotype/human-phenotype-ontology/blob/master/.travis.yml

but many ontologies simply install the very basic one:

https://github.com/obophenotype/c-elegans-phenotype-ontology/blob/master/.travis.yml

Does that help?

**Comment by matentzn** [comment]
Maybe you can piece together from here how to use fastobo in the ODK:
https://github.com/INCATools/ontology-development-kit/pull/215

**Comment by chambm** [comment]
I think the second link will serve nicely. Thanks!

**Comment by matentzn** [comment]
Let me know if you need further help!

**Comment by chambm** [comment]
I actually ended up doing it with GitHub actions instead of TravisCI, but it would've worked either way: https://github.com/HUPO-PSI/psi-ms-CV/blob/master/.github/workflows/validate-obo.yml

**Comment by matentzn** [comment]
Very nice!
