### ISSUE TITLE
make: owltools: No such file or directory 

### ISSUE THREAD

**Issue by citmejia** [INCATools/ontology-development-kit#359]
Hi,

Some time ago, I created an ontology (MCO) using the Ontology Starter Kit. Now, someone else in my lab is going to edit it. He has cloned the repository, made some edits, and he tried to compile the whole thing. This error message came out:

make: owltools: No such file or directory 

I realized that in the starter kit, in the same directory as the Makefile, there is a directory called bin in which there are some files called owltools. Then, when I tried to add and push this directory to the remote repository, I received this message:

The following paths are ignored by one of your .gitignore files:
bin

Do I have to share the bin directory with him so he can work on the ontology? 
Why is this directory included in a file .gitignore?

Sorry if these questions are basic, I am a biologist, not a computer scientist, but I am doing my best to understand all of this.

**Comment by matentzn** [comment]
Hey @citmejia!

You are trying to build your repository without using docker! This will be a bit more difficult. As a general rule, we always avoid to commit binary files; and nowadays, we don't do it at all anymore because all the tools required to build an ontology are in the ontology development kit docker container. Perhaps the best course of action for you would be to set up a new repo according to the instructions in the [README.md](README.md), and then copy the MCO ontology over.

If you want to send me your email, I could invite you to the OBO slack space where I could help you more easily then through github if you have problems!

**Comment by citmejia** [comment]
citlalli.mejiaalmonte@gmail.com

**Comment by matentzn** [comment]
We resolved the issue on slack! @citmejia let me know if you have further issues!
