### ISSUE TITLE
patterns skipped in Makefile

### ISSUE THREAD

**Issue by megbalk** [INCATools/ontology-development-kit#385]
@ramonawalls and I independently set up a new ontology and in both of our the pattern section was skipped in the Makefile. However, in an older ODK set up there is a pattern section in the Makefile. 

Is there code living somewhere that we can add to the Makefile to use dosdp patterns?

**Comment by matentzn** [comment]
Did you add

```
use_dosdps: TRUE
```

to your odk yaml?

**Comment by ramonawalls** [comment]
We did not. I guess that is a new thing. Perhaps the documentation can be updated.

**Comment by ramonawalls** [comment]
What is the flag for that if running on command line without yaml file?

**Comment by matentzn** [comment]
It totally needs to... sorry my bad. :/ 

since last year, it has not been possible to pass all parameters in using the command line - they simply became to many.. Hence the config file! So the idea is, you create that config file (btw: you have some kind of terrible version of it, its called porject.yml in your top level directory), and use this (and only this) to create a basic ODK setup..

Once you have the initial version created, you see that same config file in `src/ontology/o-odk.yml`, and you can update your repo using `sh run.sh make update_repo`. So for example, @megbalk would add the DOSDP parameter to the config file, and then run `sh run.sh make update_repo` in the reposity and the dodsp pipelines will appear. Same with adding an import!

You can put this also on the agenda for our call (was it next week?). Super happy to walk you through the steps on slack as well!

**Comment by matentzn** [comment]
Mind though #384

**Comment by megbalk** [comment]
thank you! I'll give that a try

**Comment by matentzn** [comment]
Let me know if there are issues. I will document this stuff in the next 2 months thoroughly!

**Comment by ramonawalls** [comment]
Thanks, @matentzn .

**Comment by matentzn** [comment]
Please let me know if there are further issues.
