### ISSUE TITLE
Experiment with Multiarch images

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#421]
@gouttegd recommended this blog post: https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way

I think its worth exploring `buildx` and multi-arch builds. @gouttegd should you ever be interested to try this, I would be interested how this works. 

So all images, for all platforms exist at the same tag, but somehow docker fetches the right one depending on the infrastructure of the client? Is this also how you understand it?

**Comment by gouttegd** [comment]
> So all images, for all platforms exist at the same tag, but somehow docker fetches the right one depending on the infrastructure of the client? Is this also how you understand it?

Yes. For an example, look at [this image for ubuntu/nginx](https://hub.docker.com/r/ubuntu/nginx/tags?page=1&ordering=last_updated). For each tag, there are several versions of the image for 3 or 4 different platforms (`amd64`, `arm64`, `ppc64`...). If I `pull ubuntu/nginx` from my M1-powered machine, I will get the `arm64` image, whereas someone pulling from a x86_64 machine will get the `amd64` image.

From my understanding of the blog post I mentioned, this is what `buildx` should allow us to do.

**Comment by gouttegd** [comment]
So I started playing with `buildx`, and here are a few observations:

1. Making it work to build multi-arch images requires a bit of tweaking of one's Docker installation. Nothing very complicated (creating a *builder* instance and using it as the default builder), but it’s probably reason enough not to use multi-arch build by default. That is, `make build` should still default to building an image for the local platform.

2. My understanding is that even after a multi-arch image has been built, `make docker-test` will only test the image for the local architecture, and I don’t think there is anything we can do about that. `buildx` makes it possible to build a arm64 image on a x86_64 machine, but the generated arm64 image cannot be *run* on the x86_64 machine and therefore cannot be tested (and the other way around: I can build a x86_64 image on my M1 but I cannot run it).

This creates the possibility that we release an image that works fine on one platform, but is broken on another, because whoever does the release and pushes the image on Docker Hub will only have been able to test for one platform. If we want to avoid that, before any release someone should take care of building the image on arm64, run the tests, and report/fix any issue. I would be happy to do that of course.

3. The `buildx build` command can take care of pushing the multi-arch to Docker Hub after generating it, and this seems the easier way to do it (I still need to explore ways). In that case we would need to change our `docker-publish` target.

**Comment by matentzn** [comment]
Awesome, thank you @gouttegd for the analysis and testing it. I think given what you are saying here, we should probably wait until buildx gets promoted from the experimental features, and the process becomes more streamlined. 

Dont go out of your way, but _if_ you have the setup working right now, feel free to try a multi-arch build on a new image/tag:

`obotools/odkfull`

Once its there, I could test it and we could just see. But - don't spend any time on it now if its too much work. I really appreciate your efforts! Thank you thank you for solving a problem that next year would have caused me big time sweat - when everyone else starts buying M1s..

**Comment by gouttegd** [comment]
I am pushing multi-arch images on `obotools/` right now.

I agree that it might be a good idea to wait a little bit for `buildx` to mature, as for now it seems a bit confusing and confused. For example, I have some trouble understanding how and when it uses the cache, as it sometimes wants to rebuild an image from scratch even without the `--no-cache` option and while the very same image has already been built five minutes ago and is therefore still in the build cache...

**Comment by gouttegd** [comment]
By the way if you could try at some point to pull `obotools/odkfull` and confirm that you end up with a amd64 image that runs fine on your machine, that would be great.

**Comment by matentzn** [comment]
Oh maaaan! Awesome! Testing right now :)

**Comment by matentzn** [comment]
Works! So awesome. Thank you so much! :) Based on your comment above, can you make a rough step by step list on what you did? Setting up your environment for buildx, what commands you ran?

**Comment by gouttegd** [comment]
First check whether `buildx` is available/enabled on your Docker installation:

```
$ docker buildx version
```

If you get a version message, all good. Otherwise you may need to at least enable `buildx` or even maybe to compile it. Your mileage may vary. On my Mac with Docker Desktop, `buildx` was already enabled, I didn't even need to enable the "experimental features" contrary to what the documentation says; on my GNU/Linux system, I needed both to compile it *and* to enable the experimental features.

Then you need to create a "builder" and to use it as the default builder for buildx. This is necessary as the default builder is unable to create multi-arch images.

```
$ docker buildx create
lucid_perlman
$ docker buildx use lucid_perlman
```

The name returned by `buildx create` may vary depending on your platform and/or Docker versions (it was `lucid_perlman` on my Mac, `festive_driscoll` on my GNU/Linux; where do those names come from is anyone's guess).

Then, on GNU/Linux you need to make sure to have an emulator able to run binaries for all the platforms for which you want to build images. In my case for example, I needed `qemu-arm64` to run arm64 binaries on my x86_64 machine. This is *not* needed on MacOS as Docker Desktop already comes with built-in QEMU emulation support.

All the above only needs to be done once, and then you are ready to build multi-arch images.

To build a multi-arch image (here for for x86_64 and arm64) and immediately push it to Docker Hub:

```
$ docker buildx build --push --platform linux/amd64,linux/arm64 -t obotools/odkfull:v1.2.28 -t obotools/odkfull:latest -t obotools/odkdev .
```

**Comment by gouttegd** [comment]
Multi-arch images are now supported and building them is part of the standard build process. Closing here.
