### ISSUE TITLE
Docs deployment does not work

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#506]
This action which works fine for [obook](https://github.com/OBOAcademy/obook/blob/master/.github/workflows/docs.yml) does not work here

https://github.com/INCATools/ontology-development-kit/blob/master/.github/workflows/docs.yml

No idea why. It seems to try an build the whole ODK in the action..

**Comment by matentzn** [comment]
Related to https://github.com/mhausenblas/mkdocs-deploy-gh-pages/issues/137

**Comment by gouttegd** [comment]
Looking at how the `mkdocs-deploy-gh-pages` action [is working](https://github.com/mhausenblas/mkdocs-deploy-gh-pages/blob/master/action.sh), the problem is that it finds our `requirements.txt` file in the root folder of the repository and tries to use it as if that file was intended for the action. It thus tries to install all of the Python modules that are part of the ODK – including some modules that contain C or C++ code that needs to be compiled but for which some non-Python dependencies are not satisfied.

Setting `REQUIREMENTS` to `none` in the environment of the action does not work, because of this:

```sh
if [ -n "${REQUIREMENTS}" ] && [ -f "${GITHUB_WORKSPACE}/${REQUIREMENTS}" ]; then
    pip install -r "${GITHUB_WORKSPACE}/${REQUIREMENTS}"
else
    REQUIREMENTS="${GITHUB_WORKSPACE}/requirements.txt"
    if [ -f "${REQUIREMENTS}" ]; then
        pip install -r "${REQUIREMENTS}"
    fi
fi
```

the action will try to look for `${GITHUB_WORKSPACE}/none`, find that it does not exist, and therefore forcefully fallback to looking for `${GITHUB_WORKSPACE}/requirements.txt`. To me this is a wrong decision of the part of `mkdocs-deploy-gh-pages`. If `REQUIREMENTS` is set to a value that does not correspond to an existing file, I believe the right thing to do would be to forego about requirements entirely instead of using a default value…

Anyway, unless and until this is fixed upstream (there’s a proposal in mhausenblas/mkdocs-deploy-gh-pages#55), the only workaround would be to rename our `requirements.txt` to anything else.

**Comment by matentzn** [comment]
Awesome! Thanks a ton!
