### ISSUE TITLE
Docker image incompatible

### ISSUE THREAD

**Issue by DanBerrios** [INCATools/ontology-development-kit#546]
I am getting this error message:

latest: Pulling from obolibrary/odkfull
docker: no matching manifest for windows/amd64 10.0.19042 in the manifest list entries.

Would it be possible to build and release a docker image that can run on this (my) system?

**Comment by matentzn** [comment]
hmmmm, this is odd! I just yesterday worked with a windows user with the latest ODK. @gouttegd do you have any idea what could cause this?

**Comment by gouttegd** [comment]
@DanBerrios Can you check that your installation of Docker is configured to run _Linux_ containers and not _Windows_ containers?

If you see an option [_Switch to Linux containers_](https://docs.docker.com/desktop/windows/#switch-between-windows-and-linux-containers) in your Docker Desktop menu, it means your Docker is presently configured to run [Windows containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/). You then need to switch to Linux containers in order to use the ODK.

**Comment by gouttegd** [comment]
> Is there any way we can get a docker build that works with these containers?

Probably not.

Several aspects of the way the ODK is built and works assume an underlying GNU/Linux system. For example, the way many programs we need are installed in the container (using Debian’s `apt-get` tool), or the way the ODK-generated Makefile depends on many “classical“ UNIX tools (`cat`, `grep`, `sh`, etc.).

That’s kind of the entire reason why we provide the ODK as a Docker image, so that we can design the ODK around a Linux base and still have it work on MacOS or Windows through the transparent Linux emulation that Docker Desktop provides on those systems.

Adapting the ODK to work on a Windows base would be tantamount to a re-design from scratch, and I doubt we could muster the time and ressources to do that. Sorry. :(

**Comment by DanBerrios** [comment]
@gouttegd I understand. I will have to battle here on my end for a solution/work around.  Thanks!  You can close...

**Comment by jamesaoverton** [comment]
@DanBerrios Sorry that ODK won't work for you, for the reasons @gouttegd lays out. But ROBOT and the various Python-based tools that ODK includes (such as DOS-DP) should still work under Windows.

**Comment by DanBerrios** [comment]
@jamesaoverton We will still use ODK, but I just need to find a linux of mac box to switch my work to...  It's only the dang WSL subsystem that NASA doesn't like.
