### ISSUE TITLE
Reconsider updating ODK QC automatically

### ISSUE THREAD

**Issue by shawntanzk** [INCATools/ontology-development-kit#563]
Currently it seems that ODK version in QC needs to be updated manually - should we make this automated?

**Comment by matentzn** [comment]
Usually everything is updated automatically, but we made a choice in the past to not update QC automatically to avoid breaking peoples pipelines for reasons that pertain to changes in the tooling. This gives us backwards compatibility, but on the other hand, introducing new features in the workflows now requires editors to manually change the CI which may be a burden. For readers of this issue:

## A breaking change for DOSDP was introduced in 1.3.0

Please make sure that you update the following file in your repo manually:

```
.github/workflows/qc.yml
```

to use 

```
container: obolibrary/odkfull:v1.3.0
```

instead of whatever older version you were using.

Example of an "old" line:

https://github.com/pato-ontology/pato/blob/master/.github/workflows/qc.yml#L22

**Comment by matentzn** [comment]
Please reopen when the question resurfaces. I am still not clear about the risks involved in doing this automatically.
