### ISSUE TITLE
ODK failing on Windows

### ISSUE THREAD

**Issue by henrietteharmse** [INCATools/ontology-development-kit#583]
I have  a user that tried to use the ODK on Windows when they try to do a `run.bat make all`, they get `Could not find or load main class '-Xmx8G'`. See screenshot below:

![image](https://user-images.githubusercontent.com/32327979/163187626-7c886bf5-0c93-48c2-aed4-f2e7f3877b13.png)

Did she use the correct commands? Or is this indeed an ODK issue?

**Comment by gouttegd** [comment]
It looks like the Windows shell is interpreting `ROBOT_JAVA_ARGS='-Xmx8G'` as if the value of `ROBOT_JAVA_ARGS` should be set to `'-Xmx8G'` (with the quotes) instead of `-Xmx8G` (without the quotes).

Therefore once inside the Docker container, the call to `robot` becomes something like

```
exec java '-Xmx8G' -jar /tools/robot.jar
```

where the presence of the opening quote in `'-Xmx8G'` prevents Java from recognising that argument as an option (since it begins with a quote, _not_ with a dash). It is thus interpreted as a class name, which of course it cannot find.

Unfortunately I cannot test as I do not have access to a Windows machine.

Could you edit the `run.bat` script and replace

```
-e ROBOT_JAVA_ARGS='-Xmx8G' -e JAVA_OPTS='-Xmx8G'
```

with

```
-e 'ROBOT_JAVA_ARGS=-Xmx8G' -e 'JAVA_OPTS=-Xmx8G'
```

(That is, moving the opening quote to before the variable being defined; this should prevent the Windows shell from thinking that the quotes are part of the value.)
