### ISSUE TITLE
`update_repo`: Remove `target/<REPO_NAME>` after completion

### ISSUE THREAD

**Issue by joeflack4** [INCATools/ontology-development-kit#669]
## Overview
When running `update_repo`, a folder called `target/<REPO_NAME>` is created. However, after `update_repo` finishes what it's doing, it leaves this folder there. This can create a problem: these files get indexed / searched by IDE and in the terminal when doing `find` / `grep` workflows, which is not what we want. We don't want a lingering `target/<REPO_NAME>` at all. The purpose of this issue is to request that after `update_repo` is finished, it deletes this folder.

## Example of where I use this
In the `mondo-ingest` repo, in `src/ontology/`, I run `sh run.sh make update_repo`.

---

@matentzn Hope this is the correct repo to put this issue

**Comment by matentzn** [comment]
Yes, thank you!

**Comment by matentzn** [comment]
In the end I decided against doing this, because there are good reasons to maintain the `target` repo _after_ the update: as their are certain files, like .gitignore or catalog.xml which are not managed by the ODK, sometimes I like to open the target folder to manually copy some files out. 

As a compromise, I added the `target` dir to the CLEAN directive https://github.com/INCATools/ontology-development-kit/pull/749
