### ISSUE TITLE
Add a validation check that the RDF/XML parses using Rust RDF/XML parser

### ISSUE THREAD

**Issue by cmungall** [INCATools/ontology-development-kit#691]
Not all RDF/XML parsers behave the same way

I have seen cases where Jena is stricter than OWLAPI, and where the Rust parser is stricter still.

E.g pipe symbols in URIs: https://github.com/monarch-initiative/vertebrate-breed-ontology/issues/51

We should ensure that RDF/XML produced is consumable by the union of all production-level parsers.

I believe fastobo wraps the Rust RDF/XML parser but fastobo itself may impose an additional level of strictness

I think rdftab is distributed with ODK so that could also be used to check.

**Comment by gouttegd** [comment]
Both Jena and Rdftab are distributed with the ODK, so we could have a standard target in which we try to read the RDF/XML release files successively with ROBOT, Jena, and Rdftab, and fail if any one of them complains.

Of note, Jena and Rdftab are (currently) only distributed in the `odkfull` image. If we want to make such a check a part of the default, standard workflow (which sounds like a good idea to me), we need to either move these programs to `odklite` or accept that the standard workflow requires `odkfull`.

**Comment by gouttegd** [comment]
After some tests:

* `rdftab` is not very convenient, as before it can be used one needs to initialize a SQLite3 database. The database file must then be cleaned up once we’re done parsing. Not a big deal, but cumbersome when all we want to do is to validate a file.
* Instead of using `rdftab`, we could use _LightRDF_, a small Python wrapper around the Rust RDF/XML parser. The library does not come with a command-line tool, but a small script would be enough.
* We could also use `rdfpipe`, part of _RDFLib_ which we already have in `odkfull`. It seems to be quite strict as well (it did catch an error similar to the one referred above). Problem: it’s very slow, likely due to the fact it’s pure Python.

So I propose:
- [ ] Add _LightRDF_ to `odklite`.
- [ ] Add to the standard workflow a check using _LightRDF_. That check would be mandatory (always executed as part of the release workflow).
- [ ] Add a new ODK configuration option (`extra_rdfxml_checks` or similar). If that option is enabled and if we’re running on the `odkfull` image, then the RDF/XML files would _also_ be checked with _Jena_ and _RDFLib_.

This way, we get a systematic check using what seems to be the strictest parser (the Rust one), and the possibility to get even more checks with other parsers for those who want them (in case the errors caught by the Rust parser are not a strict superset of the errors caught by the other parsers).

**Comment by jamesaoverton** [comment]
It sounds to me that LightRDF is a good solution. `rdftab` is not designed to be a validator.

**Comment by balhoff** [comment]
Jena `riot` does have a `--strict` parameter, which you get automatically when you run `riot --validate`. I don't know how it compares to the Rust parser.

**Comment by gouttegd** [comment]
I did use the `-s` flag in my tests. Even with that flag, it doesn’t catch the error mentioned in this ticket (presence of invalid symbols in URIs) – only the Rust parser (and thus `lightrdf`) seems to catch this one.

**Comment by balhoff** [comment]
@gouttegd it's strange, `riot` complains in the Turtle parser but not the RDF/XML parser.
