### ISSUE TITLE
Issues with new run.sh

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#763]
1. We currently cant run things like `pip install` during a docker run because `-u` a new option to make sure written files have the correct write rights, probably deprives us of this.
2. Something is wrong with the `trap`: When the make file files (traps snaps :P), I cannot run the makefile again after that.

**Comment by matentzn** [comment]
Indeed, removing `-u $(id -u):$(id -g)` from run.sh causes the problem not to happen.

**Comment by gouttegd** [comment]
> We currently cant run things like pip install during a docker run because -u […] deprives us of this.

Yes, the problem must be that the user ID effectively used (which is the user ID of the user invoking `docker run` on the host system) has no home directory inside the image, so `pip install` cannot fallback to install the packages in the user’s local Python tree.

Not sure how we can work around this one. We cannot predict at build time what the effective user ID will be, so there’s no way we can make sure there is a home directory that belongs to the effective user.

I feel that ultimately, the most correct solution is to encourage people who need to install things (Python packages or whatever) as part of their workflows to make a custom version of the ODK image, using a very simple `Dockerfile` that just builds on top of `obolibrary/odkfull`. This is also the most efficient solution, incidentally, since it avoids downloading the packages at each invocation.

> When the make file files (traps snaps :P), I cannot run the makefile again after that.

I don’t understand, sorry.

**Comment by matentzn** [comment]
> Not sure how we can work around this one. We cannot predict at build time what the effective user ID will be, so there’s no way we can make sure there is a home directory that belongs to the effective user.

For the first iteration of this feature, I made it configurable rather than mandatory.

>> When the make file files (traps snaps :P), I cannot run the makefile again after that.

> I don’t understand, sorry.

I also do not know if it is related to the trap, but I just don't seem to be able to run the run.sh multiple times after a failure without restarting docker.. I will explore this and report back.

**Comment by matentzn** [comment]
This is ok for now.
