### ISSUE TITLE
Versioned DEV Release

### ISSUE THREAD

**Issue by balhoff** [INCATools/ontology-development-kit#764]
I was wondering if we could do frequent releases that just update versions of included software, and leave development of ODK features on a slower track. Maybe this would just be tagging some of the `dev` releases? When a new ROBOT version is released, I am usually eager to start using it in ODK.

**Comment by matentzn** [comment]
@gouttegd no rush at all on this one (as there will be an ODK release soon) but I wonder what options there are for auto-incrementing tags in docker? for dev, we don't really want to manually curate the tag (like we do for the main release). It does make sense to have a new dev tag that is stable every time I push a dev release though

**Comment by gouttegd** [comment]
The problem with using `-dev` is that there would be no guarantees that the workflows are not somehow broken. In a `-dev` “release”, there might be some upgraded versions of the bundled software _and_ some breaking changes in the standard Makefile – currently there’s no way of separating the two kinds of changes.

What we could do is to introduce something like “maintenance branches” after a release, which we would use to do _point releases_ where we only fix bugs and update to new software versions (without any changes in the workflows).

For example, let’s say we just released ODK 1.4.0. We start working on ODK 1.5.0 in the `master` branch, doing anything we need to do (including happily breaking things). At the same time, we create a `odk-1.4.0-maintenance` branch. If, say, a new ROBOT release is published, we switch to that version both in the `master` branch (so that it will be part of the upcoming 1.5.0), and we _also_ switch to it in the `odk-1.4.0-maintenance` branch, from where we can quickly make a `1.4.1` release which will only contain the new ROBOT version, no matter what we have done in the `master` branch.

I would normally be wary of using such “maintenance“ branches, as maintaining them can be a burden. But if we commit to two simple principles:
* point releases should only contain software updates and small bugfixes;
* maintenance branches should only be maintained until the next major release occurs (i.e., once 1.5.0 is out, no one should expect point releases in the 1.4.x branch);

then I think we can do it.

**Comment by gouttegd** [comment]
> We will create regular tagged releases with changes in that branch.

Not sure what you mean by “regular”. If you’re thinking about automatic releases performed at a fixed interval of time (e.g., every 2 weeks), I disagree. The decision to make a maintenance release, and when to do it, should be made on a case-by-case basis, as for major releases.

> here is a suggestion to make the maintenance branch the new edge

Again, not sure what you mean by “edge“. To me, “edge“ is the tip of the master branch, containing _all_ the new stuff that will be part (or not, if we later revert some stuff) of the next major release. That’s the `DEV` tag, which is the tip of the master branch frozen at a particular point in time.

With that meaning, the maintenance branch should emphatically _not_ be the edge.

> link latest to the latest maintenance branch update

Yes. Basically:

* `DEV`: the “edge“, containing whatever we are doing at the moment, with absolutely zero promises that using it will not break your workflows and send your edit file into `/dev/null` – and if that happens we do not even promise to help you with that, you have been warned.
* `latest`: as it says on the can: the _latest_ release we have done, independently of whether it is a major release containing brand new features or a maintenance release containing only software updates. After we release, say ODK 1.4.0, `latest` will be ODK 1.4.0; if at some point during the development cycle of ODK 1.5.0 we need to do a 1.4.1 maintenance release, `latest` will be ODK 1.4.1; then when we release ODK 1.5.0, `latest` will be ODK 1.5.0, and so on.

People who worry that even a maintenance release could break their workflows should just avoid using `latest` and use instead an explicit version number.

> the tags should be in line with what we already have I think: for the major release v1.3.1, we count up: v1.3.1.maintainance.1, v1.3.1.maintainance.2

This is needlessly complicated, though it would not have much importance if we do tag the latest maintenance release as `latest` (people will use `latest` and will never have to explicit give the full version number).

I would much rather use a versioning system that is a little bit more meaningful (closer to semantic versioning), because right now there does not seem to be any logic to determine what the next version number should be or whether a release contains “many” changes compared to the previous one. Looking at the next release on the horizon, given all the changes that it contains, numbering it 1.3.2 and calling it a “minor” release is a joke.

My suggestion would be to number the next release 1.4.0 and from that point to always increase the second number for every non-maintenance release (unless the release contains very big changes which would warrant increasing the first number instead – for example, if we have rewritten the standard workflows from scratch); the third number is kept for maintenance releases.

**Comment by matentzn** [comment]
> Not sure what you mean by “regular”. 

I mean: I will release from time to time manually :P

I agree with all the rest of what you are saying. Including the semantic versioning idea.

In this case, we don't really need to change _anything_ other than our practices, right? No pull requests, no Makefile changes needed at all (at least when we except your `latest` suggestion, which is a bit risky, but I think justifiable).

**Comment by gouttegd** [comment]
> In this case, we don't really need to change anything other than our practices, right?

Yes.

> No pull requests, no Makefile changes needed at all (at least when we except your latest suggestion

Actually no, if we tag maintenance releases as `latest`, _then_ we do not have to change anything in the Makefile. It’s if we want to do otherwise that changes would be needed.

The Makefile is designed so that `make build` will build the image and tag it with both the current version number and the `latest` tag. This is already exactly what we need if we want to use `latest` for maintenance releases.

Say the master branch is ready for the 1.4.0 release. We make sure the Makefile contains `1.4.0` as the version number, and we (that is, _you_ :D ) build and publish the images. We end up with `obolibrary/odkfull:v1.4.0` and `obolibrary/odkfull:latest` on Docker Hub, the latter being simply an alias for the former.

On master, we bump the version number in the Makefile to `1.5.0` and we start working on the next release.

Then at some point, we feel the need to make a 1.4.1 release to include the latest version of ROBOT/OAK/Konclude/whatever. We branch from the 1.4.0 release, cherry-pick the changes we want, and update the version number in the Makefile to 1.4.1. When the maintenance branch is ready for release, all we (still _you_ :D ) will have to do is to run the _same release process as usual_, the only difference being that it will have to be run from the newly created maintenance branch instead of the master branch. Then, we will end up with `obolibrary/odkfull:v1.4.1` and `obolibrary/odkfull:latest` on Docker Hub, with the latter still simply an alias for the former, without anything special to do (and of course the former `obolibrary/odkfull:v1.4.0` from the previous release will still also be there).

That’s one of the reasons I advocate for using `latest` to point to the latest release, be it a major release or a maintenance release: because it’s easier with what we have. Having `latest` only pointing to the last major release, excluding maintenance releases, would require updating the Makefile to have a special case for maintenance releases, and I am too lazy for wanting to do that. :D

**Comment by matentzn** [comment]
I am now convinced you are right and this is the way to go!

**Comment by matentzn** [comment]
There are now no more action items on this.. we will commence with your suggestion @gouttegd right after the 1.4 release.
