### ISSUE TITLE
To release slightly broken OBO Serialiser or not

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#770]
Currently (OWLAPI 4.5.22) we have the situation that 

IRIs _AND_ CURIEs in **annotation assertions** are quoted.

![image](https://user-images.githubusercontent.com/7070631/211374683-56b4fe7f-d5d7-4a66-a274-d4fb0d509730.png)

I cannot confirm @cmungall suggestion that injecting `is_metadata_tag: true` would sort out the problem for cases where the value is a CURIE, i.e. 

```
property_value: IAO:0000700 MONDO:0042489
```

becomes:

```
property_value: preferred_roots "MONDO:0042489"
```

So we have to make a big decision here:

- OPT1: We will check how hard it is to fix the OWLAPI serialised to stop excessive quoting in cases where the value is an IRI (I hope that this was the _only_ problem).
- OPT2: @cmungall says in slack that the excessive quoting is unfortunate but should not be a blocker. We could roll with it for now.
- OPT3: Delay the release of ROBOT with the new OWL API until the issue is fixed.

- [x] @hkir-dev and @gouttegd (who will prepare a separate issue on the OWL API side to outline how a fix could work) will try to work on OPT1. If the problem cannot be fixed until Friday the 20th January we (the tech team) consider going with OPT2.
- [ ] @anitacaron will make sure that other tools using OBO won't suffer from this change (OPT2). For now, we will make sure that `fastobo-validator` validates a (previously valid) OBO ontology after serialising to OWLAPI 4.5.22. Does anyone know any other tools we should test this with?

**Comment by hkir-dev** [comment]
Fix PR created: https://github.com/owlcs/owlapi/pull/1085

**Comment by gouttegd** [comment]
OWL API 4.5.24 has been released with the fix (the tag is not yet visible on GitHub, but the artifact is available on Maven Central).

I’ve rebuilt the [5.6.0-beta-2 release of Protégé](https://github.com/protegeproject/protege-distribution/releases/tag/v5.6.0-beta-2) with the new version.

**Comment by gouttegd** [comment]
> I hope that this was the only problem

For what it’s worth, I tested the new Protégé on both FBbt and Uberon (two ontologies that are using OBO as their editing format), and I saw only changes that were expected.

Things like:

```diff
-property_value: dcterms-date 2022-12-15T13:57:29Z xsd:dateTime
+property_value: dcterms-date "2022-12-15T13:57:29Z" xsd:dateTime
```

(Quoting of a literal, aka non-ID, value: expected and correct.)

```diff
-property_value: seeAlso NCBITaxon:9989 xsd:string
+property_value: seeAlso "NCBITaxon:9989" xsd:string
```

This should probably be treated as a CURIE, but since it is marked as a string, the quoting is correct. If a property value is to be treated as a CURIE then it’s up to the Uberon curators to enter the value as an ID, rather than as a literal value.

```diff
-property_value: dcterms-isReferencedBy http://www.ncbi.nlm.nih.gov/pubmed/22293552 xsd:anyURI
+property_value: dcterms-isReferencedBy "http://www.ncbi.nlm.nih.gov/pubmed/22293552" xsd:anyURI
```

Likewise. This is a literal value of type `xsd:anyURI`, _not_ an ID, so quoting it is the expected behaviour. Again, if we wanted that value to be an ID, it should have been entered as such in Protégé. It has not, so the OWL API is doing the right thing here.

The other type of change I see is the escaping of `}` characters in text values, where the previous version used to only escape `{`:

```diff
-comment: Pre-synaptic terminals were assessed by labelling with a UAS-Synaptotagmin reporter (P\{UAS-HA-syt}) [FBtp0015803].
+comment: Pre-synaptic terminals were assessed by labelling with a UAS-Synaptotagmin reporter (P\{UAS-HA-syt\}) [FBtp0015803].
```

The OBO Flat File Format does not mention this escaping (unless I’m missing something), but based on the discussion in owlcs/owlapi#828 (especially [this comment](https://github.com/owlcs/owlapi/issues/828#issuecomment-475724171)) this is intentional and expected.

**Comment by matentzn** [comment]
This is so amazing, I have never seen such a fast turnaround on such a complicated issue! Thank you all for doing this! Lets get Protege 5.6 out there asap!

**Comment by gouttegd** [comment]
> Lets get Protege 5.6 out there asap!

I am fervently hoping that 5.6.0-beta-2 can be the last beta. :)

Though I fully expect, based from past experiences with beta releases, that the moment we release the final 5.6.0 version, people who didn’t bother testing the beta will start reporting bugs… I am almost certain we will need to release a 5.6.1 before summer! :D

**Comment by matentzn** [comment]
I would expect no less :)

**Comment by matentzn** [comment]
This is now fixed. I will close the issue here, thank you so much @hkir-dev and @gouttegd to drive this mammoth act forward!
