### ISSUE TITLE
add an RDF validator to check for spaces in IRIs

### ISSUE THREAD

**Issue by balhoff** [INCATools/ontology-development-kit#892]
It seems like a validation check was added in #691, but it looks like it's still letting in issues like this: https://github.com/obo-behavior/behavior-ontology/pull/181

Or else maybe NBO is not running that check? I caught this with Jena (`tdb2.tdbloader`). Maybe we should add a conversion to Turtle then check with `riot --validate`?

**Comment by balhoff** [comment]
Also:
- https://github.com/monarch-initiative/MAxO/issues/542
- https://github.com/monarch-initiative/MAxO/issues/564

**Comment by gouttegd** [comment]
The RDF/XML validation check is disabled by default. Users must set `ensure_valid_rdfxml = True` in their ODK configuration to enable it.

We used to have a LightRDF-based validation that was fast enough to be enabled by default, but we had to disable it because of a very weird bug (#743) in either LightRDF itself or the underlying Rust parser.

**Comment by gouttegd** [comment]
It seems the #743 bug can be fixed by updating the Rio libraries used by LightRDF (https://github.com/ozekik/lightrdf/issues/14). If we can get a new LightRDF release with updated dependencies, we could re-enable the LightRDF-based RDF/XML check by default.
