### ISSUE TITLE
Ensure that update-constraints.sh updates to the latest versions of certain tools

### ISSUE THREAD

**Issue by matentzn** [INCATools/ontology-development-kit#895]
Right now, https://github.com/INCATools/ontology-development-kit/blob/master/update-constraints.sh fails to update the latest SSSOM versions for some reason. It would be good make it somehow possible to force the latest versions of certain tools, maybe the ones listed in https://github.com/INCATools/ontology-development-kit/blob/master/requirements.txt.lite.

But for now:

Why is the pipeline unable to migrate to sssom?

Here is the log. It is trying, but somehow its not succeeding: https://github.com/INCATools/ontology-development-kit/actions/runs/5529593049/jobs/10087870510 (maybe pandas dependency?)

**Comment by gouttegd** [comment]
`kgx` requires Pandas < 2.0.0 but the latest versions of `sssom` require Pandas >= 2.0.2.

**Comment by hrshdhgd** [comment]
https://github.com/INCATools/ontology-development-kit/actions/runs/5529593049/jobs/10087870510 seems to have passed. Is this still an issue?

**Comment by gouttegd** [comment]
It passed, but it didn’t pick the latest version of `sssom` – that’s what Nico is complaining about.

But there’s nothing we can do about it in the ODK itself.

Either:
* `sssom` relaxes its dependency on `pandas` to accept versions lower than 2.0, or
* `kgx` starts supporting `pandas` >= 2.0.

Until either one of those things happen, the ODK will be stuck with `0.3.32`, the last version which didn’t require `pandas` >= 2.0.

**Comment by hrshdhgd** [comment]
Made a PR in KGX : https://github.com/biolink/kgx/pull/462

**Comment by matentzn** [comment]
Can you chase to make a release as well? I guess after the release, this should be solved, hopefully :D

**Comment by matentzn** [comment]
You mean like having "runner" scripts for tools like sssom that always activate an environment before running? I guess that would be possible!

**Comment by gouttegd** [comment]
Yes. And yes, that would be possible, there is no doubt about that.

The problems with such siloed environments would be that:

* Putting them in place would increase the complexity of the ODK building process (and I’d rather _decrease_ the ODK complexity than increase it).
* It’s only a good solution for _tools_, not for _libraries_.

In the case of `sssom-py` for example, that would allow users to always get the latest _sssom_ tool, if they need to invoke that tool somewhere in their workflows. But imagine that, instead of calling the `sssom` tool, I instead have a custom Python script that imports the `sssom-py` package (maybe because I want to do something with mappings that the `sssom` tool does not support, or maybe because I already have a workflow as a large Python script and I’d rather process my mappings from within that script than invoking a shell command like `sssom`). In order to work with the siloed latest `sssom-py`, that script would need to know _where_ is the siloed environment containing `sssom-py`.

**Comment by matentzn** [comment]
Oh yes.. Good points!

**Comment by matentzn** [comment]
I did contemplate once to maintain a list of "dependencies on edge", see https://github.com/INCATools/ontology-development-kit/pull/851, but I will for now abandon this as the update process seems to work well enough recently.
